### ISSUE TITLE
drag and drop by offset

### ISSUE THREAD

**Issue by petrisorureche** [bormando/selenium-tools#6]
Can we add this functionality?

**Comment by bormando** [comment]
@petrisorionel thanks for the proposition! 👍 
It's a great idea, but I've done quick investigation and couldn't find a way to simulate drag and drop logic by offset natively on JavaScript. So I'm afraid no - I won't be able to add it. 😞

**Comment by nekdan** [comment]
@bormando 
Hi, this question is about moving an element to given coordinates?
I have a dropable element only when you bring the dragged element to it. Therefore, this script is not working for me, since the DOM-tree is being rebuilt in the process. I think translation by coordinates would be suitable for me. If this is not possible, then perhaps you can suggest another solution to my problem?

**Comment by bormando** [comment]
Hi @nekdan,
Unfortunately, browser API doesn't provide such functionality, so it isn't possible to do that with **JavaScript** construction.
[WebDriver API](https://www.w3.org/TR/webdriver1/) is the only way to do that right, but as you already know - [it stays broken for many years](https://github.com/w3c/webdriver/issues/1488).

I see only 2 solutions here:
1. Do not automate drag & drop scenarios.
2. Try another automation tool (I'd suggest [PlayWright](https://playwright.dev/) - it's available for **Python** as well).
